// Source registry mapped from uploads/sources.json.
// feeds: candidate URLs tried in order; "{rsshub}" expands to each RSSHub instance.
const RSSHUB_INSTANCES = [
  'https://rsshub.rssforever.com',
  'https://rsshub.ktachibana.party',
  'https://rsshub.app',
];

// category: article | news | podcast
const SOURCES = [
  // ---------- Newsletters & Blogs (article) ----------
  { id: 'james-clear', name: 'James Clear 3-2-1', category: 'article', siteUrl: 'https://jamesclear.com/3-2-1', enabled: true, limit: 10,
    feeds: ['https://jamesclear.com/feed'], description: '每周 3-2-1 思考通讯' },
  { id: 'bensbites', name: "Ben's Bites", category: 'article', siteUrl: 'https://www.bensbites.com', enabled: true, limit: 10,
    feeds: ['https://www.bensbites.com/feed', 'https://bensbites.beehiiv.com/feed', '{rsshub}/bensbites'], description: 'AI 日报' },
  { id: 'tldrai', name: 'TLDR AI', category: 'article', siteUrl: 'https://tldr.tech/ai', enabled: true, limit: 10,
    feeds: ['https://tldr.tech/api/rss/ai', '{rsshub}/tldr/ai'], description: 'AI 新闻速览' },
  { id: 'importai', name: 'Import AI', category: 'article', siteUrl: 'https://importai.substack.com', enabled: true, limit: 10,
    feeds: ['https://importai.substack.com/feed'], description: 'Jack Clark 的 AI 周报' },
  { id: 'nlp-elvis', name: 'NLP Newsletter (Elvis)', category: 'article', siteUrl: 'https://nlp.elvissaravia.com', enabled: true, limit: 5,
    feeds: ['https://nlp.elvissaravia.com/feed'] },
  { id: 'interconnects', name: 'Interconnects', category: 'article', siteUrl: 'https://www.interconnects.ai', enabled: true, limit: 5,
    feeds: ['https://www.interconnects.ai/feed'], description: 'Nathan Lambert 论 LLM' },
  { id: 'waitbutwhy', name: 'Wait But Why', category: 'article', siteUrl: 'https://waitbutwhy.com', enabled: true, limit: 10,
    feeds: ['https://waitbutwhy.com/feed'] },
  { id: 'yuanchaofa', name: '袁超发技术博客', category: 'article', siteUrl: 'https://yuanchaofa.com', enabled: true, limit: 10,
    feeds: ['https://yuanchaofa.com/rss.xml'] },
  { id: 'brainfood', name: 'FS Brain Food', category: 'article', siteUrl: 'https://fs.blog/brain-food/', enabled: true, limit: 10,
    feeds: ['https://fs.blog/feed/'], description: 'Farnam Street 思维模型' },
  { id: 'austinkleon', name: 'Austin Kleon', category: 'article', siteUrl: 'https://austinkleon.com', enabled: true, limit: 10,
    feeds: ['https://austinkleon.substack.com/feed', 'https://austinkleon.com/feed/'] },
  { id: 'paulgraham', name: 'Paul Graham Essays', category: 'article', siteUrl: 'https://paulgraham.com/articles.html', enabled: true, limit: 15,
    feeds: ['http://www.aaronsw.com/2002/feeds/pgessays.rss', '{rsshub}/blogs/paulgraham'] },
  { id: 'oneusefulthing', name: 'One Useful Thing', category: 'article', siteUrl: 'https://www.oneusefulthing.org', enabled: true, limit: 10,
    feeds: ['https://www.oneusefulthing.org/feed'], description: 'Ethan Mollick 谈 AI 应用' },
  { id: 'scotthyoung', name: 'Scott H. Young', category: 'article', siteUrl: 'https://www.scotthyoung.com/blog', enabled: true, limit: 10,
    feeds: ['https://www.scotthyoung.com/blog/feed/'] },
  { id: 'readwise-wise', name: 'Readwise Wise', category: 'article', siteUrl: 'https://wise.readwise.io', enabled: true, limit: 10,
    feeds: ['https://wise.readwise.io/rss', 'https://wise.readwise.io/feed'] },
  { id: 'whytryai', name: 'Why Try AI', category: 'article', siteUrl: 'https://www.whytryai.com', enabled: true, limit: 5,
    feeds: ['https://www.whytryai.com/feed'] },
  { id: 'chinai', name: 'ChinAI Newsletter', category: 'article', siteUrl: 'https://chinai.substack.com', enabled: true, limit: 5,
    feeds: ['https://chinai.substack.com/feed'], description: '中国 AI 观察' },
  { id: 'dankoe', name: 'Dan Koe Letters', category: 'article', siteUrl: 'https://thedankoe.com/letters/', enabled: true, limit: 10,
    feeds: ['https://thedankoe.com/feed/', 'https://letters.thedankoe.com/feed'] },
  { id: 'kexuefm', name: '科学空间', category: 'article', siteUrl: 'https://kexue.fm', enabled: true, limit: 10,
    feeds: ['https://kexue.fm/feed'], description: '苏剑林的 AI/ML 技术博客' },
  { id: 'tylerfolkman', name: 'Tyler Folkman', category: 'article', siteUrl: 'https://tylerfolkman.substack.com', enabled: true, limit: 5,
    feeds: ['https://tylerfolkman.substack.com/feed'] },
  { id: 'superhuman_ai', name: 'Superhuman AI', category: 'article', siteUrl: 'https://www.superhuman.ai', enabled: true, limit: 5,
    feeds: ['https://www.superhuman.ai/feed', 'sitemap:https://www.superhuman.ai/sitemap.xml'], description: 'AI 工具与技术进展日报' },
  { id: 'aibreakfast', name: 'AI Breakfast', category: 'article', siteUrl: 'https://aibreakfast.beehiiv.com', enabled: true, limit: 5,
    feeds: ['https://aibreakfast.beehiiv.com/feed', 'sitemap:https://aibreakfast.beehiiv.com/sitemap.xml'] },
  { id: 'simonwillison', name: "Simon Willison's Weblog", category: 'article', siteUrl: 'https://simonwillison.net', enabled: true, limit: 15,
    feeds: ['https://simonwillison.net/atom/everything/'], description: 'LLM/AI 工具最活跃独立博主' },
  { id: 'garymarcus', name: 'Gary Marcus', category: 'article', siteUrl: 'https://garymarcus.substack.com', enabled: true, limit: 5,
    feeds: ['https://garymarcus.substack.com/feed'], description: 'AI 批评视角' },
  { id: 'dwarkesh', name: 'Dwarkesh Patel', category: 'article', siteUrl: 'https://www.dwarkeshpatel.com', enabled: true, limit: 5,
    feeds: ['https://www.dwarkeshpatel.com/feed', 'https://www.dwarkesh.com/feed'], description: '深度访谈 AI 领袖' },
  { id: 'gwern', name: 'Gwern Branwen', category: 'article', siteUrl: 'https://gwern.net', enabled: true, limit: 5,
    feeds: ['https://gwern.substack.com/feed'] },
  { id: 'geoffreylitt', name: 'Geoffrey Litt', category: 'article', siteUrl: 'https://www.geoffreylitt.com', enabled: true, limit: 5,
    feeds: ['https://www.geoffreylitt.com/feed.xml'], description: 'AI/HCI 研究与工具设计' },
  { id: 'experimental-history', name: 'Experimental History', category: 'article', siteUrl: 'https://www.experimental-history.com', enabled: true, limit: 5,
    feeds: ['https://www.experimental-history.com/feed'] },
  { id: 'construction-physics', name: 'Construction Physics', category: 'article', siteUrl: 'https://www.construction-physics.com', enabled: true, limit: 5,
    feeds: ['https://www.construction-physics.com/feed'] },
  { id: 'antirez', name: 'antirez (Redis 作者)', category: 'article', siteUrl: 'http://antirez.com', enabled: true, limit: 5,
    feeds: ['http://antirez.com/rss'] },
  { id: 'ds-ai-section', name: 'DS AI Section', category: 'article', siteUrl: 'https://rssdsaisection.substack.com', enabled: true, limit: 5,
    feeds: ['https://rssdsaisection.substack.com/feed'] },
  { id: 'theresanaiforthat', name: "There's An AI For That", category: 'article', siteUrl: 'https://newsletter.theresanaiforthat.com', enabled: true, limit: 5,
    feeds: ['https://newsletter.theresanaiforthat.com/feed'] },

  // ---------- Aggregators (news) ----------
  { id: 'huggingface', name: 'Hugging Face Papers', category: 'news', siteUrl: 'https://huggingface.co/papers', enabled: true, limit: 15,
    feeds: ['{rsshub}/huggingface/daily-papers'], description: '每日热门论文' },
  { id: 'producthunt', name: 'Product Hunt', category: 'news', siteUrl: 'https://www.producthunt.com', enabled: true, limit: 10,
    feeds: ['https://www.producthunt.com/feed', '{rsshub}/producthunt/today'] },
  { id: 'github_trending', name: 'GitHub Trending', category: 'news', siteUrl: 'https://github.com/trending', enabled: true, limit: 15,
    feeds: ['https://mshibanami.github.io/GitHubTrendingRSS/daily/all.xml', '{rsshub}/github/trending/daily/any'] },
  { id: 'bestblogs', name: 'BestBlogs.dev', category: 'news', siteUrl: 'https://www.bestblogs.dev/articles', enabled: true, limit: 10,
    feeds: ['https://www.bestblogs.dev/feeds/rss', 'https://api.bestblogs.dev/feeds/rss'], description: '中文技术博客聚合精选' },
  { id: 'hackernews', name: 'Hacker News', category: 'news', siteUrl: 'https://news.ycombinator.com', enabled: false, limit: 10,
    note: '用户要求禁用，信息噪音太大', feeds: ['https://hnrss.org/frontpage'] },
  { id: 'reddit_ai', name: 'Reddit AI 社区', category: 'news', siteUrl: 'https://www.reddit.com/r/MachineLearning+LocalLLaMA+ClaudeAI+Anthropic/', enabled: false, limit: 8,
    note: '用户要求禁用', feeds: ['https://www.reddit.com/r/MachineLearning+LocalLLaMA+ClaudeAI+Anthropic/.rss'] },
  { id: 'hackernoon-lifehacking', name: 'HackerNoon Life Hacking', category: 'news', siteUrl: 'https://hackernoon.com/c/life-hacking', enabled: false, limit: 10,
    note: '16篇0阅读', feeds: ['https://hackernoon.com/tagged/life-hacking/feed'] },
  { id: 'hackernoon-writing', name: 'HackerNoon Writing', category: 'news', siteUrl: 'https://hackernoon.com/c/writing', enabled: false, limit: 10,
    note: '18篇0阅读', feeds: ['https://hackernoon.com/tagged/writing/feed'] },
  { id: 'hackernoon-pm', name: 'HackerNoon PM', category: 'news', siteUrl: 'https://hackernoon.com/c/product-management', enabled: false, limit: 10,
    note: '15篇0阅读', feeds: ['https://hackernoon.com/tagged/product-management/feed'] },
  { id: 'kdnuggets-ai', name: 'KDnuggets AI', category: 'news', siteUrl: 'https://www.kdnuggets.com', enabled: false, limit: 10,
    note: '92篇0阅读，纯噪音', feeds: ['https://www.kdnuggets.com/feed'] },

  // ---------- Podcasts ----------
  { id: 'lexfridman', name: 'Lex Fridman Podcast', category: 'podcast', siteUrl: 'https://lexfridman.com/podcast', enabled: true, limit: 10,
    feeds: ['https://lexfridman.com/feed/podcast/'] },
  { id: 'latentspace', name: 'Latent Space', category: 'podcast', siteUrl: 'https://www.latent.space', enabled: true, limit: 10,
    feeds: ['https://www.latent.space/feed'], description: 'AI 工程师播客' },
  { id: 'cognitiverevolution', name: 'Cognitive Revolution', category: 'podcast', siteUrl: 'https://www.cognitiverevolution.ai', enabled: false, limit: 10,
    note: '用户明确表示不感兴趣 (AI safety/policy)', feeds: ['https://feeds.megaphone.fm/RINTP3108857801'] },
  { id: 'hours80k', name: '80,000 Hours Podcast', category: 'podcast', siteUrl: 'https://80000hours.org/podcast/', enabled: false, limit: 10,
    feeds: ['https://feeds.transistor.fm/80000-hours-podcast'] },

  // ---------- Disabled newsletters ----------
  { id: 'dcthemedian', name: 'DC The Median', category: 'article', siteUrl: 'https://dcthemedian.substack.com', enabled: false, limit: 3,
    note: '10篇0阅读', feeds: ['https://dcthemedian.substack.com/feed'] },
  { id: 'markmcneilly', name: 'Mark McNeilly', category: 'article', siteUrl: 'https://markmcneilly.substack.com', enabled: false, limit: 3,
    note: '12篇0阅读', feeds: ['https://markmcneilly.substack.com/feed'] },
  { id: 'businessanalytics', name: 'Business Analytics', category: 'article', siteUrl: 'https://businessanalytics.substack.com', enabled: false, limit: 3,
    feeds: ['https://businessanalytics.substack.com/feed'] },
  { id: 'therundown', name: 'The Rundown AI', category: 'article', siteUrl: 'https://www.therundown.ai', enabled: false, limit: 3,
    note: '与 TLDR AI 重复覆盖', feeds: ['https://rss.beehiiv.com/feeds/2R3C6Bt5wj.xml'] },
  { id: 'theneuron', name: 'The Neuron Daily', category: 'article', siteUrl: 'https://www.theneurondaily.com', enabled: false, limit: 3,
    note: '与 TLDR AI/Rundown 重复', feeds: ['https://rss.beehiiv.com/feeds/N4eCstxvgX.xml'] },
  { id: 'aileadershipedge', name: 'AI Leadership Edge', category: 'article', siteUrl: 'https://theaileadershipedge.substack.com', enabled: false, limit: 3,
    feeds: ['https://theaileadershipedge.substack.com/feed'] },
  { id: 'memia', name: 'Memia (Ben Reid)', category: 'article', siteUrl: 'https://memia.substack.com', enabled: false, limit: 5,
    note: '15篇0阅读', feeds: ['https://memia.substack.com/feed'] },
  { id: 'ai2roi', name: 'AI to ROI', category: 'article', siteUrl: 'https://ai2roi.substack.com', enabled: false, limit: 5,
    feeds: ['https://ai2roi.substack.com/feed'] },
  { id: 'natesnewsletter', name: "Nate's Newsletter", category: 'article', siteUrl: 'https://natesnewsletter.substack.com', enabled: false, limit: 5,
    note: '企业AI战略方向，用户明确不感兴趣', feeds: ['https://natesnewsletter.substack.com/feed'] },
  { id: 'aichangeseverything', name: 'AI Changes Everything', category: 'article', siteUrl: 'https://patmcguinness.substack.com', enabled: false, limit: 5,
    note: '12篇0阅读', feeds: ['https://patmcguinness.substack.com/feed'] },
  { id: 'shewritesai', name: 'She Writes AI', category: 'article', siteUrl: 'https://shewritesai.substack.com', enabled: false, limit: 5,
    note: '11篇0阅读', feeds: ['https://shewritesai.substack.com/feed'] },
  { id: 'lolitataub', name: 'Lolita Taub', category: 'article', siteUrl: 'https://lolitataub.substack.com', enabled: false, limit: 5,
    note: 'VC方向不匹配', feeds: ['https://lolitataub.substack.com/feed'] },
  { id: 'aitalks', name: 'AI Talks', category: 'article', siteUrl: 'https://aitalks.blog', enabled: false, limit: 5,
    note: '7篇0阅读', feeds: ['https://aitalks.blog/feed/'] },
];

module.exports = { SOURCES, RSSHUB_INSTANCES };
